name: variant
version: 1.3.1
description: Roslin Variant Pipeline v1.3.1
root: /ifs/work/bergerm1/Innovation/sandbox/ian/roslin-pipelines
binding:
  core: bin
  data: resources
  output: outputs
  workspace: workspace
  extra:
    - /scratch
    - /ifs
dependencies:
  core:
    version:
      min: 1.0.0
      max: 1.0.0
  cmo:
    version: 1.9.2
    install-path: /home/johnsoni/cmo_tools