export BUILD_THREADS="{{ build_threads }}"
export INSTALL_CORE="{{ build_core }}"
export BUILD_DOCKER="{{ buildDocker }}"
export BUILD_SINGULARITY="{{ buildSingularity }}"
export DOCKER_REGISTRY="{{ dockerRegistry }}"
export DOCKER_PUSH="{{ dockerPush }}"